[global]
project_id = "koesipeybsasrknvgntg"

[api]
url = "https://koesipeybsasrknvgntg.supabase.co"
service_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvZXNpcGV5YnNhc3JrbnZnbnRnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjkzODYzMSwiZXhwIjoyMDU4NTE0NjMxfQ.yH6Jj0nvLU4R6zP2yawDq7XCgo1rI-MU6pdDY16E7U4"
