version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: fruteria_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fruteria_nina
      MYSQL_USER: fruteria_nina
      MYSQL_PASSWORD: Admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fruteria_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: fruteria_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fruteria_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build: .
    container_name: fruteria_backend
    environment:
      FLASK_ENV: production
      DB_HOST: mysql
      DB_USER: fruteria_nina
      DB_PASSWORD: Admin123
      DB_NAME: fruteria_nina
      REDIS_HOST: redis
      SECRET_KEY: ${SECRET_KEY:-fruteria_nina_secret_key_2024_super_secure}
      CORS_ORIGINS: http://localhost:3000,http://frontend:3000
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fruteria_network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/monitoring/health"]
      timeout: 10s
      retries: 5
      start_period: 30s

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fruteria_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fruteria_network

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: fruteria_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - fruteria_network

volumes:
  mysql_data:
  redis_data:

networks:
  fruteria_network:
    driver: bridge