import { Timestamp } from 'firebase/firestore';

export type AlertType = 'fecha' | 'síntoma' | 'inactividad';
export type AlertTrigger = 'fecha_programada' | 'texto_IA' | 'falta_sesión';
export type AlertUrgency = 'baja' | 'media' | 'alta';
export type AlertStatus = 'activa' | 'resuelta' | 'cancelada';

export interface ClinicalAlert {
  id: string;
  centerId: string;
  patientId: string;
  type: AlertType;
  description: string;
  trigger: AlertTrigger;
  scheduledFor?: string; // ISO date string
  urgency: AlertUrgency;
  status: AlertStatus;
  createdBy: string; // UID del profesional
  resolvedBy?: string; // UID del profesional que resolvió
  resolvedAt?: Date;
  notes?: string; // Notas adicionales
  
  // Campos para automatización
  autoGenerated: boolean;
  sourceSessionId?: string; // Si fue generada por análisis de sesión
  lastTriggered?: Date;
  
  // Campos para notificaciones
  notificationSent: boolean;
  notificationChannels: ('email' | 'whatsapp' | 'sms')[];
  whatsappMessageId?: string;
  
  // Metadatos
  createdAt: Timestamp | Date;
  updatedAt: Timestamp | Date;
}

export interface AlertFormData {
  patientId: string;
  type: AlertType;
  description: string;
  trigger: AlertTrigger;
  scheduledFor?: string;
  urgency: AlertUrgency;
  notes?: string;
  notificationChannels: ('email' | 'whatsapp' | 'sms')[];
}

export interface AlertFilters {
  search?: string;
  patientId?: string;
  type?: AlertType | '';
  urgency?: AlertUrgency | '';
  status?: AlertStatus | '';
  createdBy?: string;
  dateRange?: {
    start?: string;
    end?: string;
  };
  autoGenerated?: boolean;
}

export interface AlertStats {
  total: number;
  active: number;
  resolved: number;
  cancelled: number;
  byType: Record<AlertType, number>;
  byUrgency: Record<AlertUrgency, number>;
  autoGenerated: number;
  pendingNotifications: number;
}

// Constantes para alertas
export const ALERT_TYPES: AlertType[] = ['fecha', 'síntoma', 'inactividad'];
export const ALERT_TRIGGERS: AlertTrigger[] = ['fecha_programada', 'texto_IA', 'falta_sesión'];
export const ALERT_URGENCIES: AlertUrgency[] = ['baja', 'media', 'alta'];
export const ALERT_STATUSES: AlertStatus[] = ['activa', 'resuelta', 'cancelada'];

export const ALERT_TYPE_LABELS: Record<AlertType, string> = {
  'fecha': 'Fecha específica',
  'síntoma': 'Síntoma detectado',
  'inactividad': 'Inactividad del paciente'
};

export const ALERT_TRIGGER_LABELS: Record<AlertTrigger, string> = {
  'fecha_programada': 'Fecha programada',
  'texto_IA': 'Análisis de IA',
  'falta_sesión': 'Falta de sesión'
};

export const ALERT_URGENCY_LABELS: Record<AlertUrgency, string> = {
  'baja': 'Baja',
  'media': 'Media',
  'alta': 'Alta'
};

export const ALERT_STATUS_LABELS: Record<AlertStatus, string> = {
  'activa': 'Activa',
  'resuelta': 'Resuelta',
  'cancelada': 'Cancelada'
};

export const ALERT_URGENCY_COLORS: Record<AlertUrgency, string> = {
  'baja': '#4caf50',
  'media': '#ff9800',
  'alta': '#f44336'
};

export const ALERT_STATUS_COLORS: Record<AlertStatus, string> = {
  'activa': '#2196f3',
  'resuelta': '#4caf50',
  'cancelada': '#9e9e9e'
};

// Configuración de notificaciones WhatsApp
export interface WhatsAppTemplate {
  id: string;
  name: string;
  language: string;
  components: {
    type: 'HEADER' | 'BODY' | 'FOOTER';
    parameters?: { type: 'TEXT'; text: string }[];
  }[];
}

export const WHATSAPP_TEMPLATES: Record<string, WhatsAppTemplate> = {
  patient_reminder: {
    id: 'patient_reminder',
    name: 'patient_session_reminder',
    language: 'es',
    components: [
      {
        type: 'BODY',
        parameters: [
          { type: 'TEXT', text: '{{1}}' }, // Nombre del paciente
          { type: 'TEXT', text: '{{2}}' }, // Fecha y hora
          { type: 'TEXT', text: '{{3}}' }  // Nombre del profesional
        ]
      }
    ]
  },
  professional_alert: {
    id: 'professional_alert',
    name: 'professional_alert',
    language: 'es',
    components: [
      {
        type: 'BODY',
        parameters: [
          { type: 'TEXT', text: '{{1}}' }, // Tipo de alerta
          { type: 'TEXT', text: '{{2}}' }, // Nombre del paciente
          { type: 'TEXT', text: '{{3}}' }  // Descripción
        ]
      }
    ]
  },
  emergency_alert: {
    id: 'emergency_alert',
    name: 'emergency_alert',
    language: 'es',
    components: [
      {
        type: 'HEADER'
      },
      {
        type: 'BODY',
        parameters: [
          { type: 'TEXT', text: '{{1}}' }, // Nombre del paciente
          { type: 'TEXT', text: '{{2}}' }  // Descripción de la crisis
        ]
      }
    ]
  }
};

// Log de acciones de alertas
export interface AlertActionLog {
  id: string;
  centerId: string;
  alertId: string;
  action: 'created' | 'triggered' | 'resolved' | 'cancelled' | 'notification_sent' | 'notification_failed';
  performedBy: string; // 'system' para acciones automáticas
  details: string;
  timestamp: Date;
  metadata?: Record<string, any>;
}